### ISSUE TITLE
FLAG NO COMPRESSION 

### ISSUE THREAD

**Issue by xocasdashdash** [DaveRandom/LibDNS#11]
Hi!

on the file https://github.com/DaveRandom/LibDNS/blob/master/src/Records/TypeDefinitions/TypeDefinitionManager.php#L225 the OR operation with the constant FLAG_NO_COMPRESSION makes it throw the following exception on https://github.com/DaveRandom/LibDNS/blob/master/src/Records/Types/TypeBuilder.php#61, if you comment out the code it works as it should. 

My version of php is 64 bits (PHP_INT_SIZE = 8) and I´m currently running the code on a mac os x with the following binary

> PHP 5.6.27 (cli) (built: Oct 15 2016 09:29:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

What´s the use of this flag? is it necessary? reading the RFC 2782 it seems that no name compression should be used but it´s not defined what that is.

**Comment by DaveRandom** [comment]
This issue has been resolved in the upcoming [version 3](https://github.com/DaveRandom/LibDNS/tree/dev/v3) release, the RR definition and processing architecture has been completely reworked.

**Comment by xocasdashdash** [comment]
Thank you!! :)

**Comment by DaveRandom** [comment]
@xocasdashdash note that v3 constitutes essentially a complete rewrite of the lib, and there are some BC breaks. I will be documenting migration requirements. I am aiming for 2nd Feb for first RC.

Most of the BC breaks just require changing some name references and making the code simpler, though.

I apologise for the amount of time it has taken me to get to this, I recently realised that the reason I wasn't doing anything with this project is because I hated the codebase :-P

**Comment by xocasdashdash** [comment]
@DaveRandom Please don't apologize! It's an awesome library!!
I think it could be the library used by the react php project: https://github.com/reactphp/dns/issues/42 so keep up the good work :)

**Comment by kelunik** [comment]
@xocasdashdash You can use https://github.com/amphp/dns and keep all your ReactPHP libraries working with https://github.com/amphp/react-adapter.

**Comment by xocasdashdash** [comment]
@kelunik yeah, in that issue I was more looking into reaping out the DNS related code from react php and using this library, same thing that's being done with amphp/dns project.

**Comment by kelunik** [comment]
@DaveRandom Any change to get this fixed in 2.x?
