### ISSUE TITLE
Decoding Error on valid domain with dot (.) MX-Record

### ISSUE THREAD

**Issue by ArneTR** [DaveRandom/LibDNS#8]
When trying to do an MX lookup for **jahoo.de** I get _Empty domain name at position 0x28
_
The MX-Record for this domain looks really a bit weird though. Result from **dig** on Google-DNS (8.8.8.8)

`
; <<>> DiG 9.8.3-P1 <<>> jahoo.de mx @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57232
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jahoo.de.          IN  MX

;; ANSWER SECTION:
jahoo.de.       21505   IN  MX  0 .

;; Query time: 29 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Apr 24 16:07:48 2016
;; MSG SIZE  rcvd: 41
`

**Comment by DaveRandom** [comment]
Fixed in master (v3)
